#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

echo "ansible-playbook -t install -t set-ssh -t brave -t wsl -t install-yq -t neovim -t github-cli local.yml --ask-bec
ome-pass"
## pull ansible
#sudo ansible-pull -U https://github.com/rajguru7/sys-set-up.git
