#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## change http remote to ssh
git remote set-url origin git@github.com:rajguru7/sys-set-up.git

# removing brave, docker as they are not required in wsl
if [ "$1" = complete ]; then
    ansible-playbook -t install -t set-ssh -t git-personal-xps -t wsl -t install-yq -t neovim -t github-cli -t python -t java -t go local.yml --ask-become-pass
else
    echo "ansible-playbook -t install -t set-ssh -t git-personal-xps -t wsl -t install-yq -t neovim -t github-cli -t python local.yml --ask-become-pass"
fi

echo -e "for private data connect ssd and download private directories(learn,finance,work,rough,apply,zsh_history) from ssd using below command in zsh:\nwsl-backupdisk.bash download"
## pull ansible
#sudo ansible-pull -U https://github.com/rajguru7/sys-set-up.git
