- hosts: localhost
  vars_prompt:
    - name: vault_username
      prompt: 1password username?
      private: false
    - name: vault_secret_key
      prompt: 1password secret key?
    - name: vault_master_password
      prompt: 1password master password?
  vars:
    key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    learn: "{{ lookup('env', 'HOME') }}/learn"
    notes: "{{ lookup('env', 'HOME') }}/notes"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - pw-manager
      - set-ssh
      - install
      - install-yq
      - github-cli
      - wsl
      - neovim
      - docker
      - python
      - java
      - go
  tasks:
    - import_tasks: tasks/pw-manager.yaml
    - import_tasks: tasks/ssh-setup.yaml
      tags:
        - set-ssh
    - import_tasks: tasks/git-setup.yaml
    - import_tasks: tasks/core-setup.yaml
    - import_tasks: tasks/gh-cli.yaml
      tags:
       - github-cli
    - import_tasks: tasks/wsl-setup.yaml
      tags:
        - wsl
    - import_tasks: tasks/zsh-setup.yaml
      tags:
        - neovim
        - kali
    - import_tasks: tasks/personal-projects.yaml
    - import_tasks: tasks/vim-setup.yaml
    - import_tasks: tasks/nvim-setup.yaml
      tags:
        - neovim
        - kali
    - import_tasks: tasks/brave.yaml
    - import_tasks: tasks/dotfiles.yaml
    - import_tasks: tasks/docker-setup.yaml
      tags:
        - docker
    - import_tasks: tasks/js-setup.yaml
      tags:
        - js
        - python
        - kali
    - import_tasks: tasks/python-setup.yaml
      tags:
        - python
        - kali
    - import_tasks: tasks/java-setup.yaml
      tags:
        - java
    - import_tasks: tasks/go-setup.yaml
      tags:
        - go
