- name: install terminal tools
  become: true
  apt:
    name: [ wget,tree,bat,zip,unzip,xclip,jq,fd-find,fzf,tmux,curl,ripgrep ]
  tags:
    - install
    - neovim
- name: install yq
  become: true
  community.general.snap:
    name:
      - snapd
      - yq
  tags:
    - install-yq #snap installs don't work in docker
- name: install network tools
  become: true
  apt:
    name: [ wireshark,traceroute,net-tools,hping3 ]
  tags:
    - install
    - network
- name: install documentation tools
  become: true
  apt:
    name: [ pandoc,texlive,librsvg2-bin ]
  tags:
    - install
- name: install neovim prereqs
  become: true
  apt:
    name: [ ninja-build,gettext,cmake ] #curl, unzip already done
  tags:
    - neovim
