- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "saurabhrajguru7@gmail.com" # can't keep random email as
  tags:                                # contributions don't get counted
  - git-personal-xps
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Saurabh Rajguru"
  tags:
  - git-personal-xps
- name: Set Git commit signing
  git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
  tags:
  - git-personal-xps
- name: Set commit singing with ssh
  git_config:
    name: gpg.format
    scope: global
    value: "ssh"
  tags:
  - git-personal-xps
- name: provide git with path to signing key
  git_config:
    name: user.signingkey
    scope: global
    value: "{{ key_path }}.pub"
  tags:
  - git-personal-xps
- name: set default branch name to main
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
  tags:
  - git-personal-xps

