- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "saurabhrajguru@xps.local"
  tags:
  - git-personal-xps
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Saurabh Rajguru"
  tags:
  - git-personal-xps
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "saurabhrajguru@mac-air.local"
  tags:
  - git-personal-mac-air
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Saurabh Rajguru"
  tags:
  - git-personal-mac-air
