- name: Install nvm
  shell:
    cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash"
    chdir: "{{ lookup('env', 'HOME') }}"
    executable: /usr/bin/zsh
- name: Install node
  shell:
    cmd: source ~/.zshrc && nvm install node
    chdir: "{{ lookup('env', 'HOME') }}"
    executable: /usr/bin/zsh
