- name: telegram-monitor exists
  stat:
    path: "{{ personal }}/telegram-monitor"
  register: telemonitor
  tags:
    - install
    - personal-project
- name: Personal Project telegram-monitor
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/telegram-monitor.git'
    dest: "{{ personal }}/telegram-monitor"
  tags:
    - install
    - personal-project
  when: telemonitor.stat.exists == False
- name: mkdocs-puml-mod exists
  stat:
    path: "{{ personal }}/mkdocs-puml-mod"
  register: mkpuml
  tags:
    - install
    - personal-project
- name: Personal Project mkdocs-puml-mod
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/mkdocs-puml-mod.git'
    dest: "{{ personal }}/mkdocs-puml-mod"
  tags:
    - install
    - personal-project
  when: mkpuml.stat.exists == False
