- name: ctf exists
  stat:
    path: "{{ ctf }}"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project ctf
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/ctf.git'
    dest: "{{ ctf }}"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
