- name: telegram-monitor exists
  stat:
    path: "{{ personal }}/telegram-monitor"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project telegram-monitor
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/telegram-monitor.git'
    dest: "{{ personal }}/telegram-monitor"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: mkdocs-puml-mod exists
  stat:
    path: "{{ personal }}/mkdocs-puml-mod"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project mkdocs-puml-mod
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/mkdocs-puml-mod.git'
    dest: "{{ personal }}/mkdocs-puml-mod"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: ctf exists
  stat:
    path: "{{ ctf }}"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project ctf
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/ctf.git'
    dest: "{{ ctf }}"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: notes exists
  stat:
    path: "{{ notes }}"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project notes
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/notes.git'
    dest: "{{ notes }}"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False

