- name: telegram-monitor exists
  stat:
    path: "{{ personal }}/telegram-monitor"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project telegram-monitor
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/telegram-monitor.git'
    dest: "{{ personal }}/telegram-monitor"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: mkdocs-puml-mod exists
  stat:
    path: "{{ personal }}/mkdocs-puml-mod"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project mkdocs-puml-mod
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/mkdocs-puml-mod.git'
    dest: "{{ personal }}/mkdocs-puml-mod"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: netsec exists
  stat:
    path: "{{ learn }}/netsec"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: learn netsec
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/netsec.git'
    dest: "{{ learn }}/netsec"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: networks exists
  stat:
    path: "{{ learn }}/networks"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: learn networks
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/networks.git'
    dest: "{{ learn }}/networks"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: isp exists
  stat:
    path: "{{ learn }}/isp"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project isp
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/isp.git'
    dest: "{{ learn }}/isp"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: ctf exists
  stat:
    path: "{{ learn }}/ctf"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project ctf
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/ctf.git'
    dest: "{{ learn }}/ctf"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False
- name: notes exists
  stat:
    path: "{{ notes }}"
  register: dir_exists
  tags:
    - install
    - personal-project
- name: Personal Project notes
  ansible.builtin.git:
    repo: 'git@github.com:rajguru7/notes.git'
    dest: "{{ notes }}"
  tags:
    - install
    - personal-project
  when: dir_exists.stat.exists == False

