- name: add key 1password apt repo
  become: true
  shell: curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  tags:
    - pw-manager
    - set-ssh
- name: add 1password apt repo
  become: true
  shell: echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list
  tags:
    - pw-manager
    - set-ssh
- name: add debsig verify policy
  become: true
  shell: 'sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/ && \
  curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol && \
  sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22 && \
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg'
  tags:
    - pw-manager
    - set-ssh
# - name: install 1password # client not required for wsl
#   become: true
#   apt:
#     update_cache: true
#     name: 1password
#   tags:
#     - pw-client
- name: install 1password cli
  become: true
  apt: 
    update_cache: true
    name: 1password-cli
  tags:
    - pw-manager
    - set-ssh

