- name: install pyenv
  shell: "curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash"
- name: install python build dependencies for pyenv
  become: true
  apt:
    name: [ build-essential, libssl-dev, zlib1g-dev, libbz2-dev, libreadline-dev, libsqlite3-dev, curl, libncursesw5-dev, xz-utils, tk-dev, libxml2-dev, libxmlsec1-dev, libffi-dev, liblzma-dev ]
- name: install python 3.12.0 and set as global
  shell: 
    cmd: source ~/.zshrc && pyenv update && pyenv install 3.12.0 && pyenv global 3.12.0
    executable: /usr/bin/zsh
- name: install pipx for global cli tools
  shell:
    cmd: source ~/.zshrc && pip install pipx
    chdir: "{{ lookup('env', 'HOME') }}"
    executable: /usr/bin/zsh
- name: install tldr
  shell:
    cmd: source ~/.zshrc && pipx install tldr
    chdir: "{{ lookup('env', 'HOME') }}"
    executable: /usr/bin/zsh
- name: install npm for pyright
  become: true
  apt:
    name: npm
  tags:
    - nvim-lsp
