- name: install wsl helper tools
  become: true
  apt:
    name: [ wslu, dos2unix ]
- name: fix wsl clock
  become: true
  shell:  "{{ lookup('env', 'HOME') }}/personal/sys-set-up/tools/wsl-time-fix"
