#!/usr/bin/bash
# Fix time sync issues in WSL
# https://github.com/microsoft/WSL/issues/8204#issuecomment-1338334154
sudo apt install -y systemd-timesyncd
sudo mkdir -p /etc/systemd/system/systemd-timesyncd.service.d
sudo tee /etc/systemd/system/systemd-timesyncd.service.d/override.conf > /dev/null <<EOF
[Unit]
ConditionVirtualization=
EOF
sudo systemctl daemon-reload
sudo systemctl start systemd-timesyncd
